name: run-azure-data-factory-pipeline
run-name: ${{ github.actor }} deployed at ${{ github.run_id }}
on: [workflow_dispatch]
env:
  AZ_DF_NAME: adfmdb
  AZ_DF_PIPELINE: "CopyJsonToMongoDBAtlas"
  AZ_DF_RESOURCE_GROUP: "rg-demo"
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}
    - name: configure az cli
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
    - name: add datafactory extension
      run: |
        az extension add --name datafactory
    - name: run pipeline
      run: |
        az datafactory pipeline create-run --factory-name ${{ env.AZ_DF_NAME }} --parameters "{\"SourceStore_Location\":\"files\", \"SourceStore_Directory\":\"\", \"DestinationStore_Location\":\"files\", \"SourceStore_Directory\":\"done\"}" --name ${{ env.AZ_DF_PIPELINE }} --resource-group ${{ env.AZ_DF_RESOURCE_GROUP }} 
